/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vdeudas;
import Datos.vventas;
import Logica.LOcultarColumna;
import Logica.StyloTabla;
import Logica.fdeudas;
import Logica.fventa;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Ayala
 */
public class frmDeudas extends javax.swing.JInternalFrame {

    public static String x;

    public frmDeudas() {
        initComponents();

        NroPago();
        centrar();
        mostrar("");
//        jPanel2.setBackground(new Color(0, 102, 100, 200));

        StyloTabla st = new StyloTabla();
        st.stylotabla(tablalistado);
        setSize(940, 650);
        setTitle("DEUDAS");
        TXTID.setVisible(false);
        txtidcliente.setVisible(false);
        cancelar();
        
        LOcultarColumna.modjtable(tablalistado);
    }

    void ocultar_columna() {
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);

        tablalistado.getColumnModel().getColumn(6).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(6).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(6).setPreferredWidth(0);

    }

    void centrar() {
        //codigo para centrar internalframe
        x = "x";
        int a = frmprincipal.jDesktopPane2.getWidth() - this.getWidth();
        int b = frmprincipal.jDesktopPane2.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true);
    }

   

    void nuevo() {
        Calendar mifecha = new GregorianCalendar();
        dcfecha.setCalendar(mifecha);
        txtpagado.setEnabled(true);
        txtpagado.requestFocus();

    }

    void cancelar() {
        txtpagado.setEnabled(false);
        TXTID.setText("");
        txtcliente.setText("");
        txttotal_deuda.setText("");
        txtpagado.setText("0");
        dcfecha.setCalendar(null);

    }
    public static DecimalFormat formateador = new DecimalFormat("0000000");//damos formato al numero de factura

    public static void NroPago() {

        fventa funcion = new fventa();

        int NroPago = funcion.NroPago();//llamamos la funcion nrofactura
        txtnumpago.setText(formateador.format(NroPago));//asignamos el numero de factura al txt

    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            for (int c = 0; c < tablalistado.getColumnCount(); c++) {

                Class<?> col_class = tablalistado.getColumnClass(c);

                tablalistado.setDefaultEditor(col_class, null); // remove editor
            }
            fdeudas func = new fdeudas();
            modelo = func.mostrar(buscar);

            tablalistado.setModel(modelo);
//            ocultar_columna();
//            lbltotalregistros.setText("Total Registros: " + Integer.toString(func.TotalRegistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txttotal_deuda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpagado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnpagar = new javax.swing.JButton();
        TXTID = new javax.swing.JTextField();
        dcfecha = new com.toedter.calendar.JDateChooser();
        txtidcliente = new javax.swing.JTextField();
        txtnumpago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("LISTA DE CLIENTES CON DEUDAS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 40));

        txtcliente.setEnabled(false);
        jPanel2.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, 30));

        jLabel1.setText("CLIENTE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        txttotal_deuda.setEnabled(false);
        jPanel2.add(txttotal_deuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 100, 30));

        jLabel2.setText("TOTAL DEUDA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 100, -1));

        jLabel3.setText("ULTIMO PAGO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        txtpagado.setEnabled(false);
        txtpagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpagadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpagadoKeyReleased(evt);
            }
        });
        jPanel2.add(txtpagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 100, 30));

        jLabel4.setText("MONTO A PAGAR");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, -1));

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, 30));

        jLabel5.setText("BUSCAR POR NOMBRE O NUM. DE  DOCUMENTO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        btnpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caja.png"))); // NOI18N
        btnpagar.setText("PAGAR");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, 40));

        TXTID.setEnabled(false);
        jPanel2.add(TXTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 30));

        dcfecha.setEnabled(false);
        jPanel2.add(dcfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 30));

        txtidcliente.setEnabled(false);
        jPanel2.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 30, 30));

        txtnumpago.setEnabled(false);
        txtnumpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumpagoKeyReleased(evt);
            }
        });
        jPanel2.add(txtnumpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 100, 30));

        jLabel7.setText("NUMERO PAGO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 200));

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablalistado.getTableHeader().setResizingAllowed(false);
        tablalistado.getTableHeader().setReorderingAllowed(false);
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablalistado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 920, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private String accion = "guardar";
    private void txtidpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpersonaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked

        accion = "Editar";
//        btnpagar.setText("Editar");
//        nuevo();

        try {
            int fila = tablalistado.rowAtPoint(evt.getPoint());
            TXTID.setText(tablalistado.getValueAt(fila, 0).toString());
            txtcliente.setText(tablalistado.getValueAt(fila, 1).toString());
            txttotal_deuda.setText(tablalistado.getValueAt(fila, 3).toString());
            txtidcliente.setText(tablalistado.getValueAt(fila, 6).toString());

        } catch (Exception e) {
        }
        nuevo();


    }//GEN-LAST:event_tablalistadoMouseClicked

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased
    void insertarpago() {
        vventas datos = new vventas();
        fventa funcion = new fventa();

        datos.setEstado("PAGADO");
        datos.setIdusuarios(Integer.parseInt(frmprincipal.lblcodusuario.getText()));
        datos.setIdpaciente(Integer.parseInt(txtidcliente.getText()));
        datos.setSaldo(Long.parseLong("0"));
        datos.setTotal(Long.parseLong(txtpagado.getText().replaceAll("\\.", "")));
        datos.setDescuento(Long.parseLong("0"));
        datos.setIdmovimiento(Integer.parseInt(frmprincipal.idcaja1));

        Calendar cal = dcfecha.getCalendar();
        int a, m, d;
        a = cal.get(cal.YEAR) - 1900;
        m = cal.get(cal.MONTH);
        d = cal.get(cal.DAY_OF_MONTH);

        datos.setFecha(new Date(a, m, d));
        datos.setNro_factura(txtnumpago.getText());
        datos.setTipo("DEUDA");

        if (funcion.insertarVentas(datos)) {

        }
//            funcion.insertarVentas(datos);
//            frmprincipal.mostrarhoy(frmprincipal.lblidmovimiento2.getText());
//            imsertarDetalle();
//        System.out.println("pagado");
//        funcion.insertarVentas(datos);
    }
    void guardarPago(){
         if (txtcliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "DEBES SELECCIONAR UN CLIENTE");
            txttotal_deuda.requestFocus();
            return;
        }
        if (txtpagado.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "EL MONTO DEL PAGO NO PUEDE ESTAR VACIO");
            txtpagado.requestFocus();
            return;
        }

        if (txtpagado.getText().equals("0")) {
            JOptionPane.showMessageDialog(rootPane, "EL MONTO DEL PAGO NO PUEDE SER 0");
            txtpagado.requestFocus();
            return;
        }

        vdeudas dts = new vdeudas();
        fdeudas func = new fdeudas();

//        datos.setMonto(Long.parseLong(txtMonto.getText().replaceAll("\\.", "")));
        Long deuda = Long.parseLong(txttotal_deuda.getText().replaceAll("\\.", ""));
        Long monto = Long.parseLong(txtpagado.getText().replaceAll("\\.", ""));
        Long total = deuda - monto;

        if (accion.equals("Editar") && total <= 0) {
            if (monto > deuda) {
                JOptionPane.showMessageDialog(null, "El monto a pagar no puede ser mayor a la deuda");
            } else {

                dts.setIddeuda(Integer.parseInt(TXTID.getText()));
                dts.setTotal_deuda(deuda - monto);

                dts.setEstado("PAGADO");

                Calendar cal = dcfecha.getCalendar();
                int a, m, d;
                a = cal.get(cal.YEAR) - 1900;
                m = cal.get(cal.MONTH);
                d = cal.get(cal.DAY_OF_MONTH);

                dts.setFecha_pago(new Date(a, m, d));

//              dts.setIdmovimiento(Integer.parseInt(txtidmovimiento.getText()));
                func.editar(dts);//editamos el saldo de la deuda

               
                JOptionPane.showMessageDialog(this, "Pago total realizado con exito");
                insertarpago();//guardamos lo que se pago
                mostrar("");
                cancelar();
                NroPago();
                 //funcion para obtener datos en frmprincipal
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                frmprincipal.mostrarhoy(dtf.format(LocalDateTime.now()));

            }

        } else {
            if (total > 0) {
                if (monto > deuda) {
                    JOptionPane.showMessageDialog(null, "El monto a pagar no puede ser mayor a la deuda");
                } else {
//                      JOptionPane.showMessageDialog(panelboton2, "sobra saldo "+total);
                    dts.setIddeuda(Integer.parseInt(TXTID.getText()));
                    dts.setTotal_deuda(deuda - monto);
                    dts.setEstado("PENDIENTE");

                    Calendar cal = dcfecha.getCalendar();
                    int a, m, d;
                    a = cal.get(cal.YEAR) - 1900;
                    m = cal.get(cal.MONTH);
                    d = cal.get(cal.DAY_OF_MONTH);

                    dts.setFecha_pago(new Date(a, m, d));

                    func.editar(dts);

                   
                    insertarpago();//guardamos lo que se pago
                    JOptionPane.showMessageDialog(this, "Pago parcial realizado con exito");

                    mostrar("");
                    cancelar();
                    NroPago();
                     //funcion para obtener datos en frmprincipal
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                frmprincipal.mostrarhoy(dtf.format(LocalDateTime.now()));

                }
//           
            }
        }

    }
    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
guardarPago();
       
    }//GEN-LAST:event_btnpagarActionPerformed
    DecimalFormat format = new DecimalFormat("###,###.##");
    private void txtpagadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagadoKeyReleased
        txtpagado.setText(txtpagado.getText().replaceAll("\\.", ""));
        int c = Integer.parseInt(txtpagado.getText());
        txtpagado.setText(format.format(c) + "");
    }//GEN-LAST:event_txtpagadoKeyReleased

    private void txtnumpagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumpagoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumpagoKeyReleased

    private void txtpagadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardarPago();
         }
    }//GEN-LAST:event_txtpagadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDeudas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDeudas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTID;
    private javax.swing.JButton btnpagar;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtidcliente;
    public static javax.swing.JTextField txtnumpago;
    private javax.swing.JTextField txtpagado;
    public static javax.swing.JTextField txttotal_deuda;
    // End of variables declaration//GEN-END:variables
}
