/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.LOcultarColumna;
import Logica.fpacientes;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Ayala
 */
public class frmvistapa_venta extends javax.swing.JFrame {

    public static DefaultTableModel modelo;
    public static int dondebuscar = 0;

    /**
     * Creates new form frmvistapaciente
     */
    public frmvistapa_venta() {
        initComponents();
//        mostrar("");
        setLocationRelativeTo(null);
        tablapaciente.setEnabled(true);
        LOcultarColumna.modjtable(tablapaciente);
    }

//    public void mostrar(String buscar) {
//        try {
//            DefaultTableModel modelo;
//            //De declara un objeto del tipo DefoutableModel llamdo "modelo"
//            fpacientes func = new fpacientes();
//            modelo = func.mostrar(buscar);
//            //Se llama al metodo mostrar de fPais que contiene el modelo de la tabla
//            tablapaciente.setModel(modelo);
//            lbltotalregistros.setText("Total Registro " + func.totalregistros);
//// LOcultarColumna.ocultar_esta_columna3(tablalistado, 0, 1, 8, 11);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    void seleccionar_esta_filapa(int fila) {

        if (dondebuscar == 1) {

            frmventas.txtcodcliente.setText(tablapaciente.getValueAt(fila, 0).toString());
            frmventas.txtcliente.setText(tablapaciente.getValueAt(fila,1).toString() + " " + tablapaciente.getValueAt(fila, 2).toString());
            frmventas.btnbProducto.requestFocus();
            this.dispose();
        }
        if (dondebuscar == 2) {

            frmcompras.lblidcliente.setText(tablapaciente.getValueAt(fila, 0).toString());
            frmcompras.txtcliente.setText(tablapaciente.getValueAt(fila, 1).toString() + " " + tablapaciente.getValueAt(fila, 2).toString());
            frmcompras.btnb_Cliente.requestFocus();
            this.dispose();
        }

    }

    public static void buscador() {

        if (dondebuscar == 1) {
            fpacientes func = new fpacientes();
            modelo = func.mostrar(txtbuscar.getText());
            tablapaciente.setModel(modelo);
            LOcultarColumna ocultar = new LOcultarColumna();
            ocultar.ocultar_esta_columna(tablapaciente, 0);
        }
        if (dondebuscar == 2) {
            fpacientes func = new fpacientes();
            modelo = func.mostrar(txtbuscar.getText());
            tablapaciente.setModel(modelo);
            LOcultarColumna ocultar = new LOcultarColumna();
            ocultar.ocultar_esta_columna(tablapaciente, 0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablapaciente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbltotalregistros = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablapaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablapaciente.getTableHeader().setResizingAllowed(false);
        tablapaciente.getTableHeader().setReorderingAllowed(false);
        tablapaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapacienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablapacienteMousePressed(evt);
            }
        });
        tablapaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablapacienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablapaciente);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clientes");

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setText("Registros");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("BUSCAR:");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbltotalregistros))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 10, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltotalregistros)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablapacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapacienteMouseClicked
        int fila = tablapaciente.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            seleccionar_esta_filapa(fila);
        }
    }//GEN-LAST:event_tablapacienteMouseClicked

    private void tablapacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapacienteMousePressed

        int fila = tablapaciente.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            seleccionar_esta_filapa(fila);
        }

    }//GEN-LAST:event_tablapacienteMousePressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        fpacientes func = new fpacientes();
        modelo = func.mostrar(txtbuscar.getText());
        tablapaciente.setModel(modelo);
        LOcultarColumna.ocultar_esta_columna(tablapaciente, 0);
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tablapacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablapacienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int fila = tablapaciente.getSelectedRow();
            seleccionar_esta_filapa(fila);
        }
    }//GEN-LAST:event_tablapacienteKeyPressed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tablapaciente.requestFocus();
            tablapaciente.changeSelection(0, 0, false, false);//sirve para selecionar una fila y una columna especifica
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmvistapa_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmvistapa_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmvistapa_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmvistapa_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmvistapa_venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltotalregistros;
    public static javax.swing.JTable tablapaciente;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
