/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vproductos;
import Logica.LOcultarColumna;
import Logica.StyloTabla;
import Logica.fpacientes;
import Logica.fproductos;
import Logica.fventa;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Ayala
 */
public class FrmVista_Servicios extends javax.swing.JFrame {

    /**
     * Creates new form FrmServicios
     */
    public FrmVista_Servicios() {
        initComponents();

//        mostrar("");
//        jPanel1.setBackground(new Color(0, 102, 100, 200));
//        jPanel2.setBackground(new Color(0, 102, 100, 200));
        StyloTabla st = new StyloTabla();

        setTitle("Vista Productos");
//        LOcultarColumna.modjtable(tablalistado);
//        LOcultarColumna.ocultar_esta_columna3(tablalistado, 0, 1, 8, 11);

    }

//    void mostrar(String buscar) {
//        try {
//            DefaultTableModel modelo;
//
//            fproductos Funcion = new fproductos();
//
//            modelo = Funcion.mostrar(buscar);
//
//            int total = Funcion.TotalRegistros;
//
//            lbltotalregistros.setText("Total Registros : " + String.valueOf(total));
//
//            tablalistado.setModel(modelo);
//            LOcultarColumna.ocultar_esta_columna3(tablalistado, 0, 1, 8, 11);
//        } catch (Exception e) {
//        }
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        lbltotalregistros = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 660));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        jLabel2.setText("BUSCAR POR CODIGO O POR PRODUCTO");

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablalistado.getTableHeader().setResizingAllowed(false);
        tablalistado.getTableHeader().setReorderingAllowed(false);
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablalistadoMousePressed(evt);
            }
        });
        tablalistado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablalistadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablalistado);

        lbltotalregistros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltotalregistros.setText("jLabel9");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("VISTA PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(395, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1059, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
         fproductos func = new fproductos();
            modelo = func.mostrar(txtbuscar.getText());
            tablalistado.setModel(modelo);
            LOcultarColumna.ocultar_esta_columnaPVenta(tablalistado, 0, 1, 3, 4, 7, 8, 9, 11, 11);
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked

    }//GEN-LAST:event_tablalistadoMouseClicked

    private void tablalistadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMousePressed
        int fila = tablalistado.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            seleccionar_esta_fila(fila);
        }
    }

    void seleccionar_esta_fila(int fila) {
        if (dondebuscar == 1) {

            fproductos cc = new fproductos();
            cc.controlarStock(tablalistado.getValueAt(fila, 0).toString());
            if (cc.cantidadproducto <= 0) {
                int confirmacion = JOptionPane.showConfirmDialog(rootPane, "EL PRODUCTO ESTA AGOTADO.. DESEAS AGREGARLO IGUAL..?");
                if (JOptionPane.OK_OPTION == confirmacion) {

                    frmventas.lblidproducto.setText(tablalistado.getValueAt(fila, 0).toString());
                    frmventas.txtproducto.setText(tablalistado.getValueAt(fila, 1).toString());
                    frmventas.txtprecio.setText(tablalistado.getValueAt(fila, 3).toString());
                    frmventas.txtcategoria.setText(tablalistado.getValueAt(fila, 9).toString());
                    frmventas.txtcantidad.setText("1");
                    frmventas.txtsubtotal.setText(tablalistado.getValueAt(fila, 3).toString());
                    frmventas.txtcantidad.requestFocus();
                    this.dispose();

                } else {
                    return;
                }
            }

            frmventas.lblidproducto.setText(tablalistado.getValueAt(fila, 0).toString());

            frmventas.txtproducto.setText(tablalistado.getValueAt(fila, 1).toString());
            frmventas.txtprecio.setText(tablalistado.getValueAt(fila, 3).toString());
            frmventas.txtsubtotal.setText(tablalistado.getValueAt(fila, 3).toString());
            frmventas.txtcategoria.setText(tablalistado.getValueAt(fila, 9).toString());
            frmventas.txtcantidad.setText("1");
            frmventas.txtcantidad.requestFocus();
            this.dispose();
        }

        if (dondebuscar == 2) {

            frmventas.txtcodcliente.setText(tablalistado.getValueAt(fila, 0).toString());
            frmventas.txtcliente.setText(tablalistado.getValueAt(fila, 3).toString());
            frmventas.btnbProducto.requestFocus();
            this.dispose();
        }
        if (dondebuscar == 3) {

            fproductos cc = new fproductos();
            cc.controlarStock(tablalistado.getValueAt(fila, 0).toString());
            if (cc.cantidadproducto <= 0) {
                int confirmacion = JOptionPane.showConfirmDialog(rootPane, "EL PRODUCTO ESTA AGOTADO.. DESEAS AGREGARLO IGUAL..?");
                if (JOptionPane.OK_OPTION == confirmacion) {

                    frmcompras.lblidproducto.setText(tablalistado.getValueAt(fila, 0).toString());
                    frmcompras.txtproducto.setText(tablalistado.getValueAt(fila, 1).toString());
                    frmcompras.txtprecio.setText(tablalistado.getValueAt(fila, 5).toString());
                    frmcompras.txtcantidad.setText("1");
                    frmcompras.idproveedor.setText(tablalistado.getValueAt(fila, 11).toString());
                    frmcompras.txtcantidad.requestFocus();
                    frmcompras.txtredondeo.setText("0");
                    frmcompras.txtsubtotal.setText("0");
                    frmcompras.txtproveedor.setText(tablalistado.getValueAt(fila, 10).toString());
                    frmcompras.txtcantidad.requestFocus();
       
                    this.dispose();

                } else {
                    return;
                }
            }

            frmcompras.lblidproducto.setText(tablalistado.getValueAt(fila, 0).toString());

            frmcompras.txtproducto.setText(tablalistado.getValueAt(fila, 1).toString());
            frmcompras.txtprecio.setText(tablalistado.getValueAt(fila, 5).toString());
            frmcompras.idproveedor.setText(tablalistado.getValueAt(fila, 11).toString());
             frmcompras.txtproveedor.setText(tablalistado.getValueAt(fila, 10).toString());
            frmcompras.txtcantidad.setText("1");
            frmcompras.txtcantidad.requestFocus();
            frmcompras.txtredondeo.setText("0");
            frmcompras.txtsubtotal.setText("0");
            
            this.dispose();
        }
         if (dondebuscar == 4) {
//
//        modelo.addColumn("ID");
//        modelo.addColumn("PRODUCTO");
//        modelo.addColumn("PRECIO UNIT.");
//        modelo.addColumn("PULGADAS");
//        modelo.addColumn("CANTIDAD");
//        modelo.addColumn("SUB TOTAL");
//        modelo.addColumn("CATEGORIA");
//        modelo.addColumn("DESC.");

// registro[0] = rs.getString("idventa");
//                registro[1] = rs.getString("idservicios");
//                registro[2] = rs.getString("idmovimiento");
//                registro[3] = rs.getString("fecha");
//                registro[4] = rs.getString("nro_factura");
//                registro[5] = rs.getString("tipo");
//                registro[6] = formatear.format(rs.getDouble("total"));
//                registro[7] = rs.getString("idpaciente");
//                registro[8] = rs.getString("cliente");
//                registro[9] = rs.getString("usuario");
             
            frmventas.txtcodcliente.setText(tablalistado.getValueAt(fila, 7).toString());
            frmventas.txtcliente.setText(tablalistado.getValueAt(fila, 8).toString());
            frmventas.txtnrofactura.setText(tablalistado.getValueAt(fila, 4).toString());
            frmventas.cbotipo.setSelectedItem(tablalistado.getValueAt(fila, 5).toString());
            frmventas.btnbProducto.requestFocus();
            this.dispose();
        }

    }

    public static DefaultTableModel modelo;
    public static int dondebuscar = 0;

    public static void buscador() {
        if (dondebuscar == 1) {
            fproductos func = new fproductos();
            modelo = func.mostrar(txtbuscar.getText());
            tablalistado.setModel(modelo);
//            LOcultarColumna ocultar = new LOcultarColumna();
//            ocultar.ocultar_esta_columna(tablalistado, 0);
//            LOcultarColumna.ocultar_esta_columna3(tablalistado, 0, 1, 8, 11);
            LOcultarColumna.ocultar_esta_columnaPVenta(tablalistado, 0, 1, 2, 4, 5, 7, 8, 10, 11);
        }
        if (dondebuscar == 2) {
            fpacientes func = new fpacientes();
            modelo = func.mostrar(txtbuscar.getText());
            tablalistado.setModel(modelo);
            LOcultarColumna ocultar = new LOcultarColumna();
            ocultar.ocultar_esta_columna(tablalistado, 0);
        }
        if (dondebuscar == 3) {
            fproductos func = new fproductos();
            modelo = func.mostrar(txtbuscar.getText());
            tablalistado.setModel(modelo);
            LOcultarColumna.ocultar_esta_columnaPVenta(tablalistado, 0, 1, 3, 4, 7, 8, 9, 11, 11);
//            LOcultarColumna ocultar = new LOcultarColumna();
//            ocultar.ocultar_esta_columna(tablalistado, 0);
        }
//         if (dondebuscar == 4) {
////              java.util.Date desde = new java.util.Date();
////        SimpleDateFormat sdf_desde = new SimpleDateFormat("yyyy-MM-dd");
//        String desde = frmprincipal.lblfechahoy.getText().replaceAll("\\/", "-");
////        String p_fecha_Desde = sdf_desde.format(desde);
//             fventa func = new fventa();
//            modelo = func.mostrarcancelacion(desde,frmventas.txtestado.getText());
//            tablalistado.setModel(modelo);
////            LOcultarColumna.ocultar_esta_columnaPVenta(tablalistado, 0, 1, 3, 4, 7, 8, 9, 11, 11);
////            LOcultarColumna ocultar = new LOcultarColumna();
////            ocultar.ocultar_esta_columna(tablalistado, 0);
//        }

    }//GEN-LAST:event_tablalistadoMousePressed

    private void tablalistadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablalistadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int fila = tablalistado.getSelectedRow();
            seleccionar_esta_fila(fila);
        }

//        int fila = tablalistado.rowAtPoint(evt.getPoint());
//        if (evt.getClickCount() == 2) {
//            seleccionar_esta_fila(fila);
//        }
    }//GEN-LAST:event_tablalistadoKeyPressed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tablalistado.requestFocus();

            tablalistado.changeSelection(0, 0, false, false);//sirve para selecionar una fila y una columna especifica
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVista_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVista_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVista_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVista_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVista_Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltotalregistros;
    public static javax.swing.JTable tablalistado;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
